### ISSUE TITLE
Stripe no longer supports API requests made with TLS 1.0

### ISSUE THREAD

**Issue by duataud** [xcarpentier/react-native-stripe-api#5]
Hi! I'm getting this error when created a new customer with Stripe.createCustomer
{error:
type: "invalid_request_error"
message: "Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls."
}

**Comment by xcarpentier** [comment]
Thank you, please let me know your configuration, device, os version, rn version.

**Comment by duataud** [comment]
I'm testing with an Xperia M  with Android 4.3. It seems that Android 4.1-4.4 dont't have activated TLS 1.2 by default. https://github.com/facebook/react-native/pull/9840#issuecomment-255516384 so the issue it's not with your library, sorry.
