### ISSUE TITLE
Secret API keys should be kept confidential

### ISSUE THREAD

**Issue by ssomnoremac** [xcarpentier/react-native-stripe-api#8]
```
API keys should be kept confidential and only stored on your own servers 
```
from the [docs](https://stripe.com/docs/dashboard#api-keys),  
```
Publishable keys only have the power to create tokens.
```

So the only thing this library should do is that and only that.

**Comment by xcarpentier** [comment]
Hello @ssomnoremac,

Interesting I will point this issue on README.
Sorry for that, it's a security SPOF.
Do you have an alternative about this ? Because create only a token is very limited ?

**Comment by ssomnoremac** [comment]
@xcarpentier , I think this still could be an extremely useful wrapper if we expanded the token creation to include all the fields listed [here](https://stripe.com/docs/api#create_card_token-card-exp_month) . Does `getCustomer` still work with the public key? I haven't tried.

Could create a nicely packaged server payload for each of the other functions and we could take an server api endpoint as an argument in the constructor.

**Comment by cooperka** [comment]
I second this issue; being react native, won't all this code ship in plaintext (zipped in the app store binary) to the client? It seems like anyone who unzips the binary would be able to charge arbitrary transactions to and from customers' credit cards using the secret API key.

Granted, the charges could only go into the bank account of whoever set up the Stripe API key, but the hacker could also theoretically refund all past charges. That would be unfortunate :(

**Comment by ssomnoremac** [comment]
I think this library still has potential to be used as a token creation module for credit cards and bank accounts and implementing both those UIs, using  RNcc-input for credit cards and I need to make a better version of the routing/account# form for banks I have. I'm planning on contributing that here. @cooperka would you review a PR? I plan to submit this weekend or so.

**Comment by xcarpentier** [comment]
@cooperka yes you are totally right !
@ssomnoremac cant wait your PR :) !

**Comment by sscaff1** [comment]
I have a FeathersJS backend for my react native app. So my code looks like this:

```javascript
this.props.feathers.service(STRIPE_SERVICE).get()
    .then((token) => {
      const client = new Stripe(token);
      // continue to do what I need to do
    })
    .catch(error => console.log(error));
```

So I have a stripe endpoint on my backend which checks and makes sure that first the request is coming from a valid client (i.e. my react native app). Then if it's coming from my RN app, the `get` method of the service returns the stripe publishable token. I think this is very secure and doesn't require any changes to your library. Feathers is just a wrapper around Express. So if your app has a backend, I think you could use this pattern regardless of what it looks like.

**Comment by cooperka** [comment]
@sscaff1 that still doesn't keep the token private... all an adversary needs to do is insert `console.log(token)` and find it in their device logs. Then they can use it to charge anyone else's bank account with your API key!

**Comment by sscaff1** [comment]
@cooperka yep I thought about that after I posted this...Thanks

**Comment by WilliamSWoodruff** [comment]
@ssomnoremac Is there a React Native Stripe repo that _doesn't_ store secret keys? loLL there's another Stripe cordova plugin that does the same thing, stores the secret key, ugh.

**Comment by ssomnoremac** [comment]
yeah, this repo still implies that you can or should create a charge directly from the client which is ridiculous and as I've stated, goes against stripe policy. I don't know to what extent @xcarpentier is maintaining this but if I PR that stuff out of here, would you push that through?

**Comment by WilliamSWoodruff** [comment]
Not exactly sure what you mean by 'push that through', I'm not a contributor to this repo nor do I have pull in the React Native community. Right now I'm considering doing the work to switch my Ionic 2 app to React Native because of frustrations with Ionic. I suggest you fork this repo onto your account and provide a subset of the functionality here, with nice payloads to be sent to an API server

**Comment by WilliamSWoodruff** [comment]
@xcarpentier This security flaw is a serious problem, unfortunately. I suggest you either deprecate this repo and open a new one with a subset of the functionality, OR release a new major version that provides as much functionality as you can without using a secret key. Having the secret key stored in the app means this plugin is broken, unfortunately. I'm sorry you put in so much work for all the functionality it seems to have, but at least you can get a contributor, @ssomnoremac if you're open to it. What do you think?

**Comment by ssomnoremac** [comment]
yeah, I'm down, it's still a great package with just the public token/ token creation service. @WilliamSWoodruff  If you have any questions about moving from ionic to RN (which I've done) hit me up on twitter @fasterpancakes.

**Comment by stokesbga** [comment]
What is the update on this?

**Comment by stokesbga** [comment]
Man please take this library down or update it! This could cause some real damage

**Comment by xcarpentier** [comment]
Hello @stokesbga @cooperka @wswoodruff,
You are totally right.
For now I just added deprecated word on the repo title and readme. 
Thanks.

**Comment by xcarpentier** [comment]
I deprecated it on npm too.

**Comment by mienaikoe** [comment]
fwiw, I think I'm not the only one who is using this library just to create tokens. It's a real issue of security to have a secret key for sure, but deprecating the whole repo feels like throwing the baby out with the bathwater. Just pare it down.

**Comment by ssomnoremac** [comment]
Yeah, I've been meaning to update this repo to pare it down. There would be great use for it to include a workflow for getting express tokens through a webView. I'm currently loading to their web interface  and then parsing the redirect url for the needed things, then leaving the webView. I agree, there's definitely use for a RN stripe npm package.

**Comment by stokesbga** [comment]
I submitted PR that removes need for secret key and added support for all fields in createToken. 

https://github.com/xcarpentier/react-native-stripe-api/pull/19
